name: Release test

on:
  push:
    branches: [ "main","CI-Setup" ]
  pull_request:
    branches: [ "main","CI-Setup" ]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --release
