name: Release test

on:
  push:
    branches: [ "main","CI-Setup" ]
  pull_request:
    branches: [ "main","CI-Setup" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --release
